# sdk/base/BUILD

cc_library(
    name = "sdk_base",
    hdrs = ["include/global_config.h"],
    strip_include_prefix = "include",  # 使用时就不需要"include/global_config.h"了
    visibility = ["//visibility:public"],  # 允许其他模块使用
)
