# sdk/BUILD

cc_library(
    name = "sdk_lib",
    deps = [
        "//sdk/key:key_lib",
        "//sdk/led:led_lib",
        "//sdk/base:sdk_base",
    ],
    visibility = ["//visibility:public"],
)
